# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zsy/softwareInstallation/clionWorkplace/dbt5-0.1.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zsy/softwareInstallation/clionWorkplace/dbt5-0.1.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zsy/softwareInstallation/clionWorkplace/dbt5-0.1.0/CMakeFiles /home/zsy/softwareInstallation/clionWorkplace/dbt5-0.1.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zsy/softwareInstallation/clionWorkplace/dbt5-0.1.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/BrokerageHouseMain

# Build rule for target.
bin/BrokerageHouseMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/BrokerageHouseMain
.PHONY : bin/BrokerageHouseMain

# fast build rule for target.
bin/BrokerageHouseMain/fast:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/build
.PHONY : bin/BrokerageHouseMain/fast

#=============================================================================
# Target rules for targets named bin/DriverMain

# Build rule for target.
bin/DriverMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/DriverMain
.PHONY : bin/DriverMain

# fast build rule for target.
bin/DriverMain/fast:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/build
.PHONY : bin/DriverMain/fast

#=============================================================================
# Target rules for targets named bin/MarketExchangeMain

# Build rule for target.
bin/MarketExchangeMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/MarketExchangeMain
.PHONY : bin/MarketExchangeMain

# fast build rule for target.
bin/MarketExchangeMain/fast:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/build
.PHONY : bin/MarketExchangeMain/fast

# target to build an object file
egen/src/AddressTable.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/AddressTable.o
.PHONY : egen/src/AddressTable.o

# target to preprocess a source file
egen/src/AddressTable.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/AddressTable.i
.PHONY : egen/src/AddressTable.i

# target to generate assembly for a file
egen/src/AddressTable.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/AddressTable.s
.PHONY : egen/src/AddressTable.s

# target to build an object file
egen/src/BaseLogger.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/BaseLogger.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/BaseLogger.o
.PHONY : egen/src/BaseLogger.o

# target to preprocess a source file
egen/src/BaseLogger.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/BaseLogger.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/BaseLogger.i
.PHONY : egen/src/BaseLogger.i

# target to generate assembly for a file
egen/src/BaseLogger.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/BaseLogger.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/BaseLogger.s
.PHONY : egen/src/BaseLogger.s

# target to build an object file
egen/src/CE.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CE.o
.PHONY : egen/src/CE.o

# target to preprocess a source file
egen/src/CE.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CE.i
.PHONY : egen/src/CE.i

# target to generate assembly for a file
egen/src/CE.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CE.s
.PHONY : egen/src/CE.s

# target to build an object file
egen/src/CETxnInputGenerator.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnInputGenerator.o
.PHONY : egen/src/CETxnInputGenerator.o

# target to preprocess a source file
egen/src/CETxnInputGenerator.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnInputGenerator.i
.PHONY : egen/src/CETxnInputGenerator.i

# target to generate assembly for a file
egen/src/CETxnInputGenerator.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnInputGenerator.s
.PHONY : egen/src/CETxnInputGenerator.s

# target to build an object file
egen/src/CETxnMixGenerator.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnMixGenerator.o
.PHONY : egen/src/CETxnMixGenerator.o

# target to preprocess a source file
egen/src/CETxnMixGenerator.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnMixGenerator.i
.PHONY : egen/src/CETxnMixGenerator.i

# target to generate assembly for a file
egen/src/CETxnMixGenerator.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CETxnMixGenerator.s
.PHONY : egen/src/CETxnMixGenerator.s

# target to build an object file
egen/src/CustomerSelection.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerSelection.o
.PHONY : egen/src/CustomerSelection.o

# target to preprocess a source file
egen/src/CustomerSelection.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerSelection.i
.PHONY : egen/src/CustomerSelection.i

# target to generate assembly for a file
egen/src/CustomerSelection.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerSelection.s
.PHONY : egen/src/CustomerSelection.s

# target to build an object file
egen/src/CustomerTable.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerTable.o
.PHONY : egen/src/CustomerTable.o

# target to preprocess a source file
egen/src/CustomerTable.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerTable.i
.PHONY : egen/src/CustomerTable.i

# target to generate assembly for a file
egen/src/CustomerTable.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/CustomerTable.s
.PHONY : egen/src/CustomerTable.s

# target to build an object file
egen/src/DM.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DM.o
.PHONY : egen/src/DM.o

# target to preprocess a source file
egen/src/DM.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DM.i
.PHONY : egen/src/DM.i

# target to generate assembly for a file
egen/src/DM.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DM.s
.PHONY : egen/src/DM.s

# target to build an object file
egen/src/DateTime.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/DateTime.o
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DateTime.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/DateTime.o
.PHONY : egen/src/DateTime.o

# target to preprocess a source file
egen/src/DateTime.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/DateTime.i
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DateTime.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/DateTime.i
.PHONY : egen/src/DateTime.i

# target to generate assembly for a file
egen/src/DateTime.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/DateTime.s
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/DateTime.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/DateTime.s
.PHONY : egen/src/DateTime.s

# target to build an object file
egen/src/EGenLogFormatterTab.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenLogFormatterTab.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenLogFormatterTab.o
.PHONY : egen/src/EGenLogFormatterTab.o

# target to preprocess a source file
egen/src/EGenLogFormatterTab.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenLogFormatterTab.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenLogFormatterTab.i
.PHONY : egen/src/EGenLogFormatterTab.i

# target to generate assembly for a file
egen/src/EGenLogFormatterTab.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenLogFormatterTab.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenLogFormatterTab.s
.PHONY : egen/src/EGenLogFormatterTab.s

# target to build an object file
egen/src/EGenVersion.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenVersion.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenVersion.o
.PHONY : egen/src/EGenVersion.o

# target to preprocess a source file
egen/src/EGenVersion.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenVersion.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenVersion.i
.PHONY : egen/src/EGenVersion.i

# target to generate assembly for a file
egen/src/EGenVersion.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/EGenVersion.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/EGenVersion.s
.PHONY : egen/src/EGenVersion.s

# target to build an object file
egen/src/InputFlatFilesStructure.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/InputFlatFilesStructure.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/InputFlatFilesStructure.o
.PHONY : egen/src/InputFlatFilesStructure.o

# target to preprocess a source file
egen/src/InputFlatFilesStructure.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/InputFlatFilesStructure.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/InputFlatFilesStructure.i
.PHONY : egen/src/InputFlatFilesStructure.i

# target to generate assembly for a file
egen/src/InputFlatFilesStructure.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/InputFlatFilesStructure.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/InputFlatFilesStructure.s
.PHONY : egen/src/InputFlatFilesStructure.s

# target to build an object file
egen/src/MEE.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEE.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEE.o
.PHONY : egen/src/MEE.o

# target to preprocess a source file
egen/src/MEE.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEE.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEE.i
.PHONY : egen/src/MEE.i

# target to generate assembly for a file
egen/src/MEE.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEE.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEE.s
.PHONY : egen/src/MEE.s

# target to build an object file
egen/src/MEEPriceBoard.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEEPriceBoard.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEEPriceBoard.o
.PHONY : egen/src/MEEPriceBoard.o

# target to preprocess a source file
egen/src/MEEPriceBoard.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEEPriceBoard.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEEPriceBoard.i
.PHONY : egen/src/MEEPriceBoard.i

# target to generate assembly for a file
egen/src/MEEPriceBoard.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEEPriceBoard.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEEPriceBoard.s
.PHONY : egen/src/MEEPriceBoard.s

# target to build an object file
egen/src/MEESecurity.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEESecurity.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEESecurity.o
.PHONY : egen/src/MEESecurity.o

# target to preprocess a source file
egen/src/MEESecurity.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEESecurity.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEESecurity.i
.PHONY : egen/src/MEESecurity.i

# target to generate assembly for a file
egen/src/MEESecurity.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEESecurity.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEESecurity.s
.PHONY : egen/src/MEESecurity.s

# target to build an object file
egen/src/MEETickerTape.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETickerTape.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETickerTape.o
.PHONY : egen/src/MEETickerTape.o

# target to preprocess a source file
egen/src/MEETickerTape.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETickerTape.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETickerTape.i
.PHONY : egen/src/MEETickerTape.i

# target to generate assembly for a file
egen/src/MEETickerTape.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETickerTape.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETickerTape.s
.PHONY : egen/src/MEETickerTape.s

# target to build an object file
egen/src/MEETradingFloor.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETradingFloor.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETradingFloor.o
.PHONY : egen/src/MEETradingFloor.o

# target to preprocess a source file
egen/src/MEETradingFloor.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETradingFloor.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETradingFloor.i
.PHONY : egen/src/MEETradingFloor.i

# target to generate assembly for a file
egen/src/MEETradingFloor.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/MEETradingFloor.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/MEETradingFloor.s
.PHONY : egen/src/MEETradingFloor.s

# target to build an object file
egen/src/Person.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Person.o
.PHONY : egen/src/Person.o

# target to preprocess a source file
egen/src/Person.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Person.i
.PHONY : egen/src/Person.i

# target to generate assembly for a file
egen/src/Person.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Person.s
.PHONY : egen/src/Person.s

# target to build an object file
egen/src/Random.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Random.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/Random.o
.PHONY : egen/src/Random.o

# target to preprocess a source file
egen/src/Random.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Random.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/Random.i
.PHONY : egen/src/Random.i

# target to generate assembly for a file
egen/src/Random.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/Random.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/Random.s
.PHONY : egen/src/Random.s

# target to build an object file
egen/src/ReadRowFunctions.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/ReadRowFunctions.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/ReadRowFunctions.o
.PHONY : egen/src/ReadRowFunctions.o

# target to preprocess a source file
egen/src/ReadRowFunctions.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/ReadRowFunctions.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/ReadRowFunctions.i
.PHONY : egen/src/ReadRowFunctions.i

# target to generate assembly for a file
egen/src/ReadRowFunctions.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/ReadRowFunctions.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/ReadRowFunctions.s
.PHONY : egen/src/ReadRowFunctions.s

# target to build an object file
egen/src/WheelTime.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/WheelTime.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/WheelTime.o
.PHONY : egen/src/WheelTime.o

# target to preprocess a source file
egen/src/WheelTime.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/WheelTime.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/WheelTime.i
.PHONY : egen/src/WheelTime.i

# target to generate assembly for a file
egen/src/WheelTime.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/WheelTime.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/WheelTime.s
.PHONY : egen/src/WheelTime.s

# target to build an object file
egen/src/error.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/error.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/error.o
.PHONY : egen/src/error.o

# target to preprocess a source file
egen/src/error.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/error.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/error.i
.PHONY : egen/src/error.i

# target to generate assembly for a file
egen/src/error.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/error.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/error.s
.PHONY : egen/src/error.s

# target to build an object file
egen/src/locking.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/locking.o
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/locking.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/locking.o
.PHONY : egen/src/locking.o

# target to preprocess a source file
egen/src/locking.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/locking.i
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/locking.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/locking.i
.PHONY : egen/src/locking.i

# target to generate assembly for a file
egen/src/locking.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/egen/src/locking.s
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/egen/src/locking.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/egen/src/locking.s
.PHONY : egen/src/locking.s

# target to build an object file
src/BrokerageHouse/BrokerageHouse.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouse.o
.PHONY : src/BrokerageHouse/BrokerageHouse.o

# target to preprocess a source file
src/BrokerageHouse/BrokerageHouse.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouse.i
.PHONY : src/BrokerageHouse/BrokerageHouse.i

# target to generate assembly for a file
src/BrokerageHouse/BrokerageHouse.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouse.s
.PHONY : src/BrokerageHouse/BrokerageHouse.s

# target to build an object file
src/BrokerageHouse/BrokerageHouseMain.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouseMain.o
.PHONY : src/BrokerageHouse/BrokerageHouseMain.o

# target to preprocess a source file
src/BrokerageHouse/BrokerageHouseMain.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouseMain.i
.PHONY : src/BrokerageHouse/BrokerageHouseMain.i

# target to generate assembly for a file
src/BrokerageHouse/BrokerageHouseMain.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/BrokerageHouse/BrokerageHouseMain.s
.PHONY : src/BrokerageHouse/BrokerageHouseMain.s

# target to build an object file
src/Customer/Customer.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Customer/Customer.o
.PHONY : src/Customer/Customer.o

# target to preprocess a source file
src/Customer/Customer.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Customer/Customer.i
.PHONY : src/Customer/Customer.i

# target to generate assembly for a file
src/Customer/Customer.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Customer/Customer.s
.PHONY : src/Customer/Customer.s

# target to build an object file
src/Driver/Driver.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/Driver.o
.PHONY : src/Driver/Driver.o

# target to preprocess a source file
src/Driver/Driver.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/Driver.i
.PHONY : src/Driver/Driver.i

# target to generate assembly for a file
src/Driver/Driver.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/Driver.s
.PHONY : src/Driver/Driver.s

# target to build an object file
src/Driver/DriverMain.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/DriverMain.o
.PHONY : src/Driver/DriverMain.o

# target to preprocess a source file
src/Driver/DriverMain.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/DriverMain.i
.PHONY : src/Driver/DriverMain.i

# target to generate assembly for a file
src/Driver/DriverMain.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/Driver/DriverMain.s
.PHONY : src/Driver/DriverMain.s

# target to build an object file
src/MarketExchange/MarketExchange.o:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchange.o
.PHONY : src/MarketExchange/MarketExchange.o

# target to preprocess a source file
src/MarketExchange/MarketExchange.i:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchange.i
.PHONY : src/MarketExchange/MarketExchange.i

# target to generate assembly for a file
src/MarketExchange/MarketExchange.s:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchange.s
.PHONY : src/MarketExchange/MarketExchange.s

# target to build an object file
src/MarketExchange/MarketExchangeMain.o:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchangeMain.o
.PHONY : src/MarketExchange/MarketExchangeMain.o

# target to preprocess a source file
src/MarketExchange/MarketExchangeMain.i:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchangeMain.i
.PHONY : src/MarketExchange/MarketExchangeMain.i

# target to generate assembly for a file
src/MarketExchange/MarketExchangeMain.s:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/MarketExchange/MarketExchangeMain.s
.PHONY : src/MarketExchange/MarketExchangeMain.s

# target to build an object file
src/interfaces/BaseInterface.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/BaseInterface.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/BaseInterface.o
.PHONY : src/interfaces/BaseInterface.o

# target to preprocess a source file
src/interfaces/BaseInterface.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/BaseInterface.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/BaseInterface.i
.PHONY : src/interfaces/BaseInterface.i

# target to generate assembly for a file
src/interfaces/BaseInterface.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/BaseInterface.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/BaseInterface.s
.PHONY : src/interfaces/BaseInterface.s

# target to build an object file
src/interfaces/CESUT.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CESUT.o
.PHONY : src/interfaces/CESUT.o

# target to preprocess a source file
src/interfaces/CESUT.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CESUT.i
.PHONY : src/interfaces/CESUT.i

# target to generate assembly for a file
src/interfaces/CESUT.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CESUT.s
.PHONY : src/interfaces/CESUT.s

# target to build an object file
src/interfaces/CSocket.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/CSocket.o
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CSocket.o
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/CSocket.o
.PHONY : src/interfaces/CSocket.o

# target to preprocess a source file
src/interfaces/CSocket.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/CSocket.i
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CSocket.i
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/CSocket.i
.PHONY : src/interfaces/CSocket.i

# target to generate assembly for a file
src/interfaces/CSocket.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/CSocket.s
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/CSocket.s
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/CSocket.s
.PHONY : src/interfaces/CSocket.s

# target to build an object file
src/interfaces/DMSUT.o:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/DMSUT.o
.PHONY : src/interfaces/DMSUT.o

# target to preprocess a source file
src/interfaces/DMSUT.i:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/DMSUT.i
.PHONY : src/interfaces/DMSUT.i

# target to generate assembly for a file
src/interfaces/DMSUT.s:
	$(MAKE) -f CMakeFiles/bin/DriverMain.dir/build.make CMakeFiles/bin/DriverMain.dir/src/interfaces/DMSUT.s
.PHONY : src/interfaces/DMSUT.s

# target to build an object file
src/interfaces/MEESUT.o:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/MEESUT.o
.PHONY : src/interfaces/MEESUT.o

# target to preprocess a source file
src/interfaces/MEESUT.i:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/MEESUT.i
.PHONY : src/interfaces/MEESUT.i

# target to generate assembly for a file
src/interfaces/MEESUT.s:
	$(MAKE) -f CMakeFiles/bin/MarketExchangeMain.dir/build.make CMakeFiles/bin/MarketExchangeMain.dir/src/interfaces/MEESUT.s
.PHONY : src/interfaces/MEESUT.s

# target to build an object file
src/interfaces/TxnHarnessSendToMarket.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/TxnHarnessSendToMarket.o
.PHONY : src/interfaces/TxnHarnessSendToMarket.o

# target to preprocess a source file
src/interfaces/TxnHarnessSendToMarket.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/TxnHarnessSendToMarket.i
.PHONY : src/interfaces/TxnHarnessSendToMarket.i

# target to generate assembly for a file
src/interfaces/TxnHarnessSendToMarket.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/interfaces/TxnHarnessSendToMarket.s
.PHONY : src/interfaces/TxnHarnessSendToMarket.s

# target to build an object file
src/transactions/BrokerVolumeDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/BrokerVolumeDB.o
.PHONY : src/transactions/BrokerVolumeDB.o

# target to preprocess a source file
src/transactions/BrokerVolumeDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/BrokerVolumeDB.i
.PHONY : src/transactions/BrokerVolumeDB.i

# target to generate assembly for a file
src/transactions/BrokerVolumeDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/BrokerVolumeDB.s
.PHONY : src/transactions/BrokerVolumeDB.s

# target to build an object file
src/transactions/CustomerPositionDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/CustomerPositionDB.o
.PHONY : src/transactions/CustomerPositionDB.o

# target to preprocess a source file
src/transactions/CustomerPositionDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/CustomerPositionDB.i
.PHONY : src/transactions/CustomerPositionDB.i

# target to generate assembly for a file
src/transactions/CustomerPositionDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/CustomerPositionDB.s
.PHONY : src/transactions/CustomerPositionDB.s

# target to build an object file
src/transactions/DataMaintenanceDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/DataMaintenanceDB.o
.PHONY : src/transactions/DataMaintenanceDB.o

# target to preprocess a source file
src/transactions/DataMaintenanceDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/DataMaintenanceDB.i
.PHONY : src/transactions/DataMaintenanceDB.i

# target to generate assembly for a file
src/transactions/DataMaintenanceDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/DataMaintenanceDB.s
.PHONY : src/transactions/DataMaintenanceDB.s

# target to build an object file
src/transactions/MarketFeedDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketFeedDB.o
.PHONY : src/transactions/MarketFeedDB.o

# target to preprocess a source file
src/transactions/MarketFeedDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketFeedDB.i
.PHONY : src/transactions/MarketFeedDB.i

# target to generate assembly for a file
src/transactions/MarketFeedDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketFeedDB.s
.PHONY : src/transactions/MarketFeedDB.s

# target to build an object file
src/transactions/MarketWatchDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketWatchDB.o
.PHONY : src/transactions/MarketWatchDB.o

# target to preprocess a source file
src/transactions/MarketWatchDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketWatchDB.i
.PHONY : src/transactions/MarketWatchDB.i

# target to generate assembly for a file
src/transactions/MarketWatchDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/MarketWatchDB.s
.PHONY : src/transactions/MarketWatchDB.s

# target to build an object file
src/transactions/SecurityDetailDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/SecurityDetailDB.o
.PHONY : src/transactions/SecurityDetailDB.o

# target to preprocess a source file
src/transactions/SecurityDetailDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/SecurityDetailDB.i
.PHONY : src/transactions/SecurityDetailDB.i

# target to generate assembly for a file
src/transactions/SecurityDetailDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/SecurityDetailDB.s
.PHONY : src/transactions/SecurityDetailDB.s

# target to build an object file
src/transactions/TradeCleanupDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeCleanupDB.o
.PHONY : src/transactions/TradeCleanupDB.o

# target to preprocess a source file
src/transactions/TradeCleanupDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeCleanupDB.i
.PHONY : src/transactions/TradeCleanupDB.i

# target to generate assembly for a file
src/transactions/TradeCleanupDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeCleanupDB.s
.PHONY : src/transactions/TradeCleanupDB.s

# target to build an object file
src/transactions/TradeLookupDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeLookupDB.o
.PHONY : src/transactions/TradeLookupDB.o

# target to preprocess a source file
src/transactions/TradeLookupDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeLookupDB.i
.PHONY : src/transactions/TradeLookupDB.i

# target to generate assembly for a file
src/transactions/TradeLookupDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeLookupDB.s
.PHONY : src/transactions/TradeLookupDB.s

# target to build an object file
src/transactions/TradeOrderDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeOrderDB.o
.PHONY : src/transactions/TradeOrderDB.o

# target to preprocess a source file
src/transactions/TradeOrderDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeOrderDB.i
.PHONY : src/transactions/TradeOrderDB.i

# target to generate assembly for a file
src/transactions/TradeOrderDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeOrderDB.s
.PHONY : src/transactions/TradeOrderDB.s

# target to build an object file
src/transactions/TradeResultDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeResultDB.o
.PHONY : src/transactions/TradeResultDB.o

# target to preprocess a source file
src/transactions/TradeResultDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeResultDB.i
.PHONY : src/transactions/TradeResultDB.i

# target to generate assembly for a file
src/transactions/TradeResultDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeResultDB.s
.PHONY : src/transactions/TradeResultDB.s

# target to build an object file
src/transactions/TradeStatusDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeStatusDB.o
.PHONY : src/transactions/TradeStatusDB.o

# target to preprocess a source file
src/transactions/TradeStatusDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeStatusDB.i
.PHONY : src/transactions/TradeStatusDB.i

# target to generate assembly for a file
src/transactions/TradeStatusDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeStatusDB.s
.PHONY : src/transactions/TradeStatusDB.s

# target to build an object file
src/transactions/TradeUpdateDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeUpdateDB.o
.PHONY : src/transactions/TradeUpdateDB.o

# target to preprocess a source file
src/transactions/TradeUpdateDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeUpdateDB.i
.PHONY : src/transactions/TradeUpdateDB.i

# target to generate assembly for a file
src/transactions/TradeUpdateDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TradeUpdateDB.s
.PHONY : src/transactions/TradeUpdateDB.s

# target to build an object file
src/transactions/TxnBaseDB.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TxnBaseDB.o
.PHONY : src/transactions/TxnBaseDB.o

# target to preprocess a source file
src/transactions/TxnBaseDB.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TxnBaseDB.i
.PHONY : src/transactions/TxnBaseDB.i

# target to generate assembly for a file
src/transactions/TxnBaseDB.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/TxnBaseDB.s
.PHONY : src/transactions/TxnBaseDB.s

# target to build an object file
src/transactions/pgsql/DBConnection.o:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/pgsql/DBConnection.o
.PHONY : src/transactions/pgsql/DBConnection.o

# target to preprocess a source file
src/transactions/pgsql/DBConnection.i:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/pgsql/DBConnection.i
.PHONY : src/transactions/pgsql/DBConnection.i

# target to generate assembly for a file
src/transactions/pgsql/DBConnection.s:
	$(MAKE) -f CMakeFiles/bin/BrokerageHouseMain.dir/build.make CMakeFiles/bin/BrokerageHouseMain.dir/src/transactions/pgsql/DBConnection.s
.PHONY : src/transactions/pgsql/DBConnection.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... bin/BrokerageHouseMain"
	@echo "... bin/DriverMain"
	@echo "... bin/MarketExchangeMain"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... egen/src/AddressTable.o"
	@echo "... egen/src/AddressTable.i"
	@echo "... egen/src/AddressTable.s"
	@echo "... egen/src/BaseLogger.o"
	@echo "... egen/src/BaseLogger.i"
	@echo "... egen/src/BaseLogger.s"
	@echo "... egen/src/CE.o"
	@echo "... egen/src/CE.i"
	@echo "... egen/src/CE.s"
	@echo "... egen/src/CETxnInputGenerator.o"
	@echo "... egen/src/CETxnInputGenerator.i"
	@echo "... egen/src/CETxnInputGenerator.s"
	@echo "... egen/src/CETxnMixGenerator.o"
	@echo "... egen/src/CETxnMixGenerator.i"
	@echo "... egen/src/CETxnMixGenerator.s"
	@echo "... egen/src/CustomerSelection.o"
	@echo "... egen/src/CustomerSelection.i"
	@echo "... egen/src/CustomerSelection.s"
	@echo "... egen/src/CustomerTable.o"
	@echo "... egen/src/CustomerTable.i"
	@echo "... egen/src/CustomerTable.s"
	@echo "... egen/src/DM.o"
	@echo "... egen/src/DM.i"
	@echo "... egen/src/DM.s"
	@echo "... egen/src/DateTime.o"
	@echo "... egen/src/DateTime.i"
	@echo "... egen/src/DateTime.s"
	@echo "... egen/src/EGenLogFormatterTab.o"
	@echo "... egen/src/EGenLogFormatterTab.i"
	@echo "... egen/src/EGenLogFormatterTab.s"
	@echo "... egen/src/EGenVersion.o"
	@echo "... egen/src/EGenVersion.i"
	@echo "... egen/src/EGenVersion.s"
	@echo "... egen/src/InputFlatFilesStructure.o"
	@echo "... egen/src/InputFlatFilesStructure.i"
	@echo "... egen/src/InputFlatFilesStructure.s"
	@echo "... egen/src/MEE.o"
	@echo "... egen/src/MEE.i"
	@echo "... egen/src/MEE.s"
	@echo "... egen/src/MEEPriceBoard.o"
	@echo "... egen/src/MEEPriceBoard.i"
	@echo "... egen/src/MEEPriceBoard.s"
	@echo "... egen/src/MEESecurity.o"
	@echo "... egen/src/MEESecurity.i"
	@echo "... egen/src/MEESecurity.s"
	@echo "... egen/src/MEETickerTape.o"
	@echo "... egen/src/MEETickerTape.i"
	@echo "... egen/src/MEETickerTape.s"
	@echo "... egen/src/MEETradingFloor.o"
	@echo "... egen/src/MEETradingFloor.i"
	@echo "... egen/src/MEETradingFloor.s"
	@echo "... egen/src/Person.o"
	@echo "... egen/src/Person.i"
	@echo "... egen/src/Person.s"
	@echo "... egen/src/Random.o"
	@echo "... egen/src/Random.i"
	@echo "... egen/src/Random.s"
	@echo "... egen/src/ReadRowFunctions.o"
	@echo "... egen/src/ReadRowFunctions.i"
	@echo "... egen/src/ReadRowFunctions.s"
	@echo "... egen/src/WheelTime.o"
	@echo "... egen/src/WheelTime.i"
	@echo "... egen/src/WheelTime.s"
	@echo "... egen/src/error.o"
	@echo "... egen/src/error.i"
	@echo "... egen/src/error.s"
	@echo "... egen/src/locking.o"
	@echo "... egen/src/locking.i"
	@echo "... egen/src/locking.s"
	@echo "... src/BrokerageHouse/BrokerageHouse.o"
	@echo "... src/BrokerageHouse/BrokerageHouse.i"
	@echo "... src/BrokerageHouse/BrokerageHouse.s"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.o"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.i"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.s"
	@echo "... src/Customer/Customer.o"
	@echo "... src/Customer/Customer.i"
	@echo "... src/Customer/Customer.s"
	@echo "... src/Driver/Driver.o"
	@echo "... src/Driver/Driver.i"
	@echo "... src/Driver/Driver.s"
	@echo "... src/Driver/DriverMain.o"
	@echo "... src/Driver/DriverMain.i"
	@echo "... src/Driver/DriverMain.s"
	@echo "... src/MarketExchange/MarketExchange.o"
	@echo "... src/MarketExchange/MarketExchange.i"
	@echo "... src/MarketExchange/MarketExchange.s"
	@echo "... src/MarketExchange/MarketExchangeMain.o"
	@echo "... src/MarketExchange/MarketExchangeMain.i"
	@echo "... src/MarketExchange/MarketExchangeMain.s"
	@echo "... src/interfaces/BaseInterface.o"
	@echo "... src/interfaces/BaseInterface.i"
	@echo "... src/interfaces/BaseInterface.s"
	@echo "... src/interfaces/CESUT.o"
	@echo "... src/interfaces/CESUT.i"
	@echo "... src/interfaces/CESUT.s"
	@echo "... src/interfaces/CSocket.o"
	@echo "... src/interfaces/CSocket.i"
	@echo "... src/interfaces/CSocket.s"
	@echo "... src/interfaces/DMSUT.o"
	@echo "... src/interfaces/DMSUT.i"
	@echo "... src/interfaces/DMSUT.s"
	@echo "... src/interfaces/MEESUT.o"
	@echo "... src/interfaces/MEESUT.i"
	@echo "... src/interfaces/MEESUT.s"
	@echo "... src/interfaces/TxnHarnessSendToMarket.o"
	@echo "... src/interfaces/TxnHarnessSendToMarket.i"
	@echo "... src/interfaces/TxnHarnessSendToMarket.s"
	@echo "... src/transactions/BrokerVolumeDB.o"
	@echo "... src/transactions/BrokerVolumeDB.i"
	@echo "... src/transactions/BrokerVolumeDB.s"
	@echo "... src/transactions/CustomerPositionDB.o"
	@echo "... src/transactions/CustomerPositionDB.i"
	@echo "... src/transactions/CustomerPositionDB.s"
	@echo "... src/transactions/DataMaintenanceDB.o"
	@echo "... src/transactions/DataMaintenanceDB.i"
	@echo "... src/transactions/DataMaintenanceDB.s"
	@echo "... src/transactions/MarketFeedDB.o"
	@echo "... src/transactions/MarketFeedDB.i"
	@echo "... src/transactions/MarketFeedDB.s"
	@echo "... src/transactions/MarketWatchDB.o"
	@echo "... src/transactions/MarketWatchDB.i"
	@echo "... src/transactions/MarketWatchDB.s"
	@echo "... src/transactions/SecurityDetailDB.o"
	@echo "... src/transactions/SecurityDetailDB.i"
	@echo "... src/transactions/SecurityDetailDB.s"
	@echo "... src/transactions/TradeCleanupDB.o"
	@echo "... src/transactions/TradeCleanupDB.i"
	@echo "... src/transactions/TradeCleanupDB.s"
	@echo "... src/transactions/TradeLookupDB.o"
	@echo "... src/transactions/TradeLookupDB.i"
	@echo "... src/transactions/TradeLookupDB.s"
	@echo "... src/transactions/TradeOrderDB.o"
	@echo "... src/transactions/TradeOrderDB.i"
	@echo "... src/transactions/TradeOrderDB.s"
	@echo "... src/transactions/TradeResultDB.o"
	@echo "... src/transactions/TradeResultDB.i"
	@echo "... src/transactions/TradeResultDB.s"
	@echo "... src/transactions/TradeStatusDB.o"
	@echo "... src/transactions/TradeStatusDB.i"
	@echo "... src/transactions/TradeStatusDB.s"
	@echo "... src/transactions/TradeUpdateDB.o"
	@echo "... src/transactions/TradeUpdateDB.i"
	@echo "... src/transactions/TradeUpdateDB.s"
	@echo "... src/transactions/TxnBaseDB.o"
	@echo "... src/transactions/TxnBaseDB.i"
	@echo "... src/transactions/TxnBaseDB.s"
	@echo "... src/transactions/pgsql/DBConnection.o"
	@echo "... src/transactions/pgsql/DBConnection.i"
	@echo "... src/transactions/pgsql/DBConnection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

